In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import  SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    df.drop(columns = ['has_covid']), df['has_covid'],test_size = 0.2
)

In [15]:
X_train

    age  gender  fever   cough       city
97   20  Female  101.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
28   16    Male  104.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
69   73  Female  103.0    Mild      Delhi
79   48  Female  103.0    Mild    Kolkata
29   34  Female    NaN  Strong     Mumbai
90   59  Female   99.0  Strong      Delhi
73   34    Male   98.0  Strong    Kolkata

[80 rows x 5 columns]

# 1. Aam Zindagi

In [24]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data

X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever

array([[101.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [100.94366197],
       [100.94366197],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [100.94366197],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [103.        ],
       [103.        ],
       [103.        ],
       [101.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.94366197],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [100.94366197],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [100.94366197],
       [100.        ],
       [101.        ],
       [103.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [100.94366197],
       [100.94366197],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [103.        ],
       [100.94366197],
       [ 99.        ],
       [ 98.        ]])

In [28]:
# Ordinal enoding -> cough
oe = OrdinalEncoder(categories = [['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

#also the test data

X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)